steps:
  - name: 'gcr.io/cloud-builders/git'
    args:
      [
        'clone',
        'https://github.com/RanduRetana/conviertoChatbot',
        'app',
      ]

  - name: 'gcr.io/cloud-builders/python'
    args: ['-m', 'pip', 'install', '-r', 'app/requirements.txt']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app/app.yaml']
